# meta.yaml
name: zender-wa
title: WhatsApp Server (Zender) - Enterprise Edition
version: "2.1.3"
description: >
  Deploys the optimized Titan Systems (Zender) WhatsApp server with enterprise features,
  multi-architecture support, session persistence, and 62% smaller image size.
instructions: null
changeLog:
  - date: 2025-09-18
    description: v2.1.3 - Security hardening with Alpine Edge and CVE patches
  - date: 2024-09-18
    description: Multi-architecture support (AMD64, ARM64, ARMv7)
  - date: 2024-09-18
    description: Alpine Linux base for better performance
  - date: 2024-09-18
    description: Advanced monitoring and health checks
  - date: 2024-09-18
    description: Automated CI/CD with GitHub Actions
  - date: 2024-09-18
    description: Template updated to trigger Docker build
  - date: 2025-07-08
    description: Use prebuilt Docker image renatoascencio/zender-wa:latest
links:
  - label: Website
    url: https://titansystems.ph
  - label: Documentation
    url: https://support.titansystems.ph/hc/articles/9/24/10/introduction
  - label: GitHub (Docker)
    url: https://github.com/RenatoAscencio/zender-wa
  - label: Docker Hub
    url: https://hub.docker.com/r/renatoascencio/zender-wa
  - label: GitHub (Templates)
    url: https://github.com/RenatoAscencio/easypanel-templates
contributors:
  - name: Renato Ascencio
    url: https://github.com/RenatoAscencio
schema:
  type: object
  required:
    - appServiceName
    - pcode
    - licenseKey
    - port
  properties:
    appServiceName:
      type: string
      title: App Service Name
      description: Name of the service in EasyPanel.
      default: zender-wa
    pcode:
      type: string
      title: Product Code (pcode)
      description: Product UUID provided by Titan Systems.
    licenseKey:
      type: string
      title: Secret Key
      description:
        Unique secure secret key. This will be used by the WhatsApp server to
        verify peer connection with Zender.
    port:
      type: integer
      title: TCP Port
      description: Port where the WhatsApp server will listen.
      default: 443
    domain:
      type: string
      title: Domain
      description: >
        Domain to expose the WhatsApp server. Defaults to your EasyPanel domain
        if not provided.
    image:
      type: string
      title: Docker Image
      description: Docker image to use for the WhatsApp server (optimized enterprise edition).
      default: renatoascencio/zender-wa:v2.1.3
    autoupdate:
      type: boolean
      title: Auto Update
      description: Automatically update the container when a new image version is available.
      default: true
benefits:
  - title: 62% Smaller Image
    description: Optimized Alpine-based image (152MB vs 398MB).
  - title: 56% Faster Startup
    description: Improved initialization time (20s vs 45s).
  - title: Multi-Architecture
    description: Supports AMD64, ARM64, and ARMv7 platforms.
  - title: Session Persistence
    description: Keeps WhatsApp sessions active between restarts.
  - title: Self Recovery
    description: Advanced health checks and auto-restart capabilities.
features:
  - title: Enterprise Edition
    description: Production-ready with advanced monitoring and logging.
  - title: Optimized Performance
    description: Alpine Linux base with minimal overhead.
  - title: Security Hardening
    description: Non-root execution and security best practices.
  - title: Automated CI/CD
    description: GitHub Actions for continuous updates.
  - title: Volume Management
    description: Persistent data storage at /data/whatsapp-server.
tags:
  - WhatsApp
  - Zender
  - EasyPanel
  - Docker
