name: zender-wa
title: Servidor WhatsApp (Zender)
version: "1.0.0"
description:
  Despliega el servidor de WhatsApp de Titan Systems (Zender) con
  persistencia de sesiones para mantener el estado de login entre reinicios.
instructions: null
changeLog:
  - date: 2025-06-29
    description: Initial Release of Zender WhatsApp EasyPanel Template
links:
  - label: Website
    url: https://titansystems.ph
  - label: Documentation
    url: https://support.titansystems.ph/hc/articles/9/24/10/introduction
  - label: GitHub
    url: https://github.com/RenatoAscencio/zender-wa-deploy
contributors:
  - name: Renato Ascencio
    url: https://github.com/RenatoAscencio
schema:
  type: object
  required:
    - pcode
    - licenseKey
    - port
  properties:
    pcode:
      type: string
      title: Código de Producto (pcode)
    licenseKey:
      type: string
      title: License Key
    port:
      type: integer
      title: Puerto TCP
      default: 443
      description: Puerto donde escuchará el servidor WhatsApp
benefits:
  - title: Persistencia de Sesiones
    description: Mantiene las sesiones de WhatsApp activas entre reinicios.
  - title: Auto-Rescate de Sesión
    description: El contenedor evita re-login tras un reinicio.
features:
  - title: Actualización Automática del Binario
    description: Descarga la última versión del servidor durante el arranque.
  - title: Auto-Monitoreo con Cron
    description: Crontab asegura que el servidor se reinicie si falla.
tags:
  - WhatsApp
  - Zender
  - EasyPanel
  - Docker