name: zender-wa
title: WhatsApp Server (Zender)
version: "1.0.3"
description: >
  Deploys the Titan Systems (Zender) WhatsApp server with session persistence to
  keep the login state between restarts.
instructions: null
changeLog:
  - date: 2025-06-29
    description: Initial release of Zender WA EasyPanel template
  - date: 2025-06-30
    description: Fix deploy command and add cron job with sleep infinity
  - date: 2025-07-01
    description: Use curl to download WA server binary
  - date: 2025-07-01
    description: Use curl to download helper scripts from GitHub
  - date: 2025-07-02
    description: Clone helper repo to /data and run install script from there
links:
  - label: Website
    url: https://titansystems.ph
  - label: Documentation
    url: https://support.titansystems.ph/hc/articles/9/24/10/introduction
  - label: GitHub
    url: https://github.com/RenatoAscencio/easypanel-templates
contributors:
  - name: Renato Ascencio
    url: https://github.com/RenatoAscencio
schema:
  type: object
  required:
    - appServiceName
    - pcode
    - licenseKey
    - port
  properties:
    appServiceName:
      type: string
      title: App Service Name
      description: Name of the service in EasyPanel.
      default: zender-wa
    pcode:
      type: string
      title: Product Code (pcode)
      description: Product UUID provided by Titan Systems.
    licenseKey:
      type: string
      title: Secret Key
      description:
        Unique secure secret key. This will be used by the WhatsApp server to
        verify peer connection with Zender.
    port:
      type: integer
      title: TCP Port
      description: Port where the WhatsApp server will listen.
      default: 443
benefits:
  - title: Session persistence
    description: Keeps WhatsApp sessions active between restarts.
  - title: Self recovery
    description: Crontab ensures the server restarts if it fails.
features:
  - title: Dependency installation
    description: Updates the system and installs wget, curl, unzip and cron.
  - title: Directory management
    description: Uses a volume mounted at /app/data/whatsapp-server.
  - title: Automatic update
    description: Downloads the latest server version using curl on each deploy.
tags:
  - WhatsApp
  - Zender
  - EasyPanel
  - Docker
